language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t l.figgins/test-client -f ./client/Dockerfile.dev ./client

script:
  #fore build
  # you need to bass the env variable through docker when using docker run
  - docker run -e CI=true l.figgins/test-client npm test

after_success:
  - docker build -t lfiggins/multi-client ./client
  - docker build -t lfiggins/multi-nginx ./nginx
  - docker build -t lfiggins/multi-server ./server
  - docker build -t lfiggins/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #login
  - docker push lfiggins/multi-client
  - docker push lfiggins/multi-nginx
  - docker push lfiggins/multi-server
  - docker push lfiggins/multi-worker
