version: "3"
services:
  client:
    image: "lfiggins/multi-client"
    mem_limit: 128m
    hostname: client
    #no build step for prod
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./client
    #remove volumes like this in production compose config
    # volumes:
    #   - /home/node/app/node_modules
    #   - ./client:/app
  api:
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./server
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    image: "lfiggins/multi-server"
    hostname: api
    environment:
      # docker services can be passed direclty when using compose
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "lfiggins/multi-worker"
    mem_limit: 128m
    hostname: worker
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./worker
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    depends_on:
      - api
      - client
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"