version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: lfiggins/multi-nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
  api:
    image: lfiggins/multi-api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app
    environment:
      # docker services can be passed direclty when using compose
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=slack_clone_backend_development
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    environment:
      - WDS_SOCKET_PORT=0
    image: lfiggins/multi-client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
  worker:
    image: lfiggins/multi-worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /home/node/app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379